### ISSUE TITLE
Add User Agent config key

### ISSUE THREAD

**Issue by eggyknap** [EndPointCorp/com.endpoint.lg.browser.service#1]
(copied from https://github.com/EndPointCorp/com.endpoint.lg.browser.static/issues/1)
We need to be able to override the browser's User Agent. Setting it to an iOS device gives us free multi-touch in Maps API.

Add config key: lg.browser.userAgent defaulting to empty string.

Override with Chrome flag: --user-agent=AGENT.

If the config key is not set, the --user-agent flag should not be appended, using the true agent.

**Comment by jonjensen** [comment]
Matt V. and Kiel don't think this is the best way to implement this and are discussing alternatives.

**Comment by jonjensen** [comment]
Matt, given your comments on the browser.static activity, what about here? If I understood you correctly, browser.service is not somewhere we currently need to mess with the user agent at all, right?

**Comment by mvollrath** [comment]
Since all of our sites are using this activity presently we'd be better off adding it as a feature of a `static_page`, i.e. `lg.browser.static_page.touchscreen.user_agent`.  To set the agent for the service-spawned instances, the flags are already exposed.

**Comment by mvollrath** [comment]
We decided not to add this feature yet.
